In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import datetime, timedelta
import seaborn as sn
import time


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

Выделяем только тех, у кого был контакт, начиная с 13 мая

In [ ]:
df = df[(df['mkb10_code'] == 'Z20.8') & (df['dis_date'] >= '2020-05-13')]
df['idx'].unique()
Contact = df['idx'].unique()

Подтвержденный U07.2


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Contact)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2') & (df['dis_date'] >= '2020-05-13')]

In [ ]:
df.shape

(5204, 17)

In [ ]:
pd.DataFrame(df['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Illness2.xlsx')

In [ ]:
Illness2 = df['idx'].unique()
Illness2

array([    164,     427,     569, ..., 1260183, 1266796, 1274932])

Acute_illness2, все из списка *Illness2*, у кого есть IgM > 1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Illness2)]

In [ ]:
df = df[df['IgM'] > 1] 

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
df

idx    pd_id  ...  samples_result_id                mu_type
428         164  1621174  ...                NaN  ��������� �����������
4204       1517  2761582  ...                NaN  ��������� �����������
12559      4139  3129070  ...                NaN  ��������� �����������
13072      4320  1560202  ...                NaN  ��������� �����������
18371      6211  1523632  ...                NaN  ��������� �����������
...         ...      ...  ...                ...                    ...
1334531  531006  4222011  ...                NaN     ��������� ��������
1337101  532518  4234800  ...                NaN  ��������� �����������
1346981  537808  4219602  ...                NaN  ��������� �����������
1347657  538238  4213171  ...                NaN  ��������� �����������
1350977  540283  4269331  ...                NaN     ��������� ��������

[1003 rows x 17 columns]

In [ ]:
pd.DataFrame(df['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Acute_illness2.xlsx')

In [ ]:
Acute_illness2 =  df['idx'].unique()

In [ ]:
Acute_illness2

array([   164,   1517,   4139,   4320,   6211,   6559,   8883,   9150,
        10394,  10874,  12402,  12403,  12480,  14563,  14862,  14918,
        15281,  15383,  16840,  17895,  17981,  18000,  19436,  20265,
        20455,  21871,  22907,  23008,  23071,  23324,  23637,  23865,
        24713,  25239,  25613,  26810,  26957,  27270,  28382,  29460,
        30386,  31622,  32780,  33178,  33474,  33667,  33914,  33928,
        34025,  34235,  35529,  35633,  35678,  35875,  37250,  37660,
        37838,  38767,  39699,  39736,  39924,  39958,  40357,  40505,
        41701,  42726,  42754,  43633,  44220,  44248,  44315,  47875,
        48519,  48838,  49880,  50158,  50459,  50596,  51450,  52055,
        53994,  54400,  55579,  55732,  57263,  57302,  57362,  61626,
        62128,  64219,  64224,  66734,  70147,  72614,  73753,  73951,
        74663,  74752,  74951,  75181,  75298,  76087,  76221,  77554,
        79950,  81373,  81604,  82787,  83438,  84565,  84683,  84991,
      

Immun_memory2, все из списка Acute_illness2, у кого тест на имунную память позже положителен, чем на острую инфекцию

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Acute_illness2)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
df

idx    pd_id  ...  samples_result_id                mu_type
428         164  1621174  ...                NaN  ��������� �����������
4204       1517  2761582  ...                NaN  ��������� �����������
12559      4139  3129070  ...                NaN  ��������� �����������
13072      4320  1560202  ...                NaN  ��������� �����������
18371      6211  1523632  ...                NaN  ��������� �����������
...         ...      ...  ...                ...                    ...
1334533  531006  3946782  ...      �� ����������     ��������� ��������
1337101  532518  4234800  ...                NaN  ��������� �����������
1346981  537808  4219602  ...                NaN  ��������� �����������
1347657  538238  4213171  ...                NaN  ��������� �����������
1350977  540283  4269331  ...                NaN     ��������� ��������

[1706 rows x 17 columns]

In [ ]:
Immun_memory2 = pd.DataFrame(Acute_illness2, columns=['idx'])

In [ ]:
def ImmGM ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] < 1) & (df['IgG'] > 10)]['get_date_at'], '2050-01-01']))

In [ ]:
def ImmM ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] > 1)]['get_date_at'], '2050-01-01']))

In [ ]:
#np.vectorize(ImmM)(Immun_memory2['idx'])

In [ ]:
#Когда тест IgM был > 1
Immun_memory2['test_day_M'] = np.vectorize(ImmM)(Immun_memory2['idx'])

In [ ]:
#Когда тест IgM < 1 & IgG > 10
Immun_memory2['test_day_G_M'] = np.vectorize(ImmGM)(Immun_memory2['idx'])

In [ ]:
Immun_memory2 = Immun_memory2[Immun_memory2['test_day_G_M'] != '2050-01-01']

In [ ]:
Immun_memory2 = Immun_memory2[Immun_memory2['test_day_G_M'] > Immun_memory2['test_day_M']]
Immun_memory2

idx  test_day_M test_day_G_M
299  164082  2020-05-27   2020-06-07
324  174164  2020-06-04   2020-06-09
404  215647  2020-06-03   2020-06-16

In [ ]:
pd.DataFrame(Immun_memory2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Immun_memory2.xlsx')

No_immun_memory, нет иммунной памяти после перенесенного заболевания
 *(второй или теретий диагноз  IgM<1, IgG<10)*

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
df = df[df['idx'].isin(Acute_illness2)]

In [ ]:
df = df[(df['mkb10_code'] == 'U07.2')]

In [ ]:
def ImmM ( idx ):
  return min(df[(df['idx'] == idx) & (df['IgM'] > 1)]['get_date_at'])


In [ ]:
np.vectorize(ImmM)(Immun_memory2['idx'])

array(['2020-05-27', '2020-06-04', '2020-06-03'], dtype='<U10')

In [ ]:
No_immun_memory2 = pd.DataFrame(Acute_illness2, columns=['idx'])

In [ ]:
#Когда тест IgM был > 1
No_immun_memory2['test_day_M'] = np.vectorize(ImmM)(No_immun_memory2['idx'])

In [ ]:
def ImmGM_no ( idx ):
  return min(np.hstack([df[(df['idx'] == idx) & (df['IgM'] < 1) & (df['IgG'] < 10)]['get_date_at'], '2050-01-01']))

In [ ]:
np.vectorize(ImmGM_no)(No_immun_memory2['idx'])

array(['2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-01-01',
       '2050-01-01', '2050-01-01', '2050-01-01', '2050-

In [ ]:
#Когда тест IgM < 1 & IgG > 10
No_immun_memory2['day_M_G'] = np.vectorize(ImmGM_no)(No_immun_memory2['idx'])

In [ ]:
No_immun_memory2 = No_immun_memory2[No_immun_memory2['day_M_G'] != '2050-01-01']

In [ ]:
No_immun_memory2 = No_immun_memory2[No_immun_memory2['day_M_G'] > No_immun_memory2['test_day_M']]

In [ ]:
No_immun_memory2['idx'].unique()

array([169796, 213164, 213953, 254444])

In [ ]:
pd.DataFrame(No_immun_memory2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/No_immun_memory2.xlsx')

Lost, группа потерянных из наблюдения

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Диплом/data_for_science (1).csv', sep=';')

In [ ]:
#из Acute illness те, кто выходят из наблюдения

df = df[df['idx'].isin(Acute_illness2)]
df = df[~df['idx'].isin(Immun_memory2['idx'])]
df = df[~df['idx'].isin(No_immun_memory2['idx'])]

In [ ]:
Lost2 = pd.DataFrame(df, columns=['idx'])

In [ ]:
Lost2['idx'].unique().shape

(787,)

In [ ]:
pd.DataFrame(Lost2['idx'].unique(), columns=['idx']).to_excel('/content/drive/MyDrive/Диплом/Lost2.xlsx')